import java.util.*;
import java.io.*;
import java.awt.*;
import static java.lang.Math.*;


public class detention{

    public void run() throws FileNotFoundException{
        System.out.println("I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n" +
                "I will not talk during this boring class.\n");
    }



    public static void main(String[] args) throws FileNotFoundException{
        new detention().run();
    }
}
